services:
  - type: web
    name: football-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: PAYPAL_EMAIL
        value: tounsii205@gmail.com
      - key: SUPABASE_REF
        value: wksopcigrtbirejcsmox
      - key: PREMIUM_PRICE
        value: "15"
